config/routes.rb
Rails.application.routes.draw do
  resources :works do
    get 'higher' => 'works#move_higher', as: 'higher', on: :member
  end
  resources :directors
  
  root 'works#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :works

    mount_uploader :image, DirectorImageUploader
end

app/models/work.rb
class Work < ApplicationRecord
    belongs_to :director

    acts_as_list scope :by_position, -> { order(position: :asc) }

    mount_uploader :image, WorkImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
    before_action :director_find, only: [:show, :edit, :update, :destroy]
    def index
        @directors = Director.all
    end
    def new
        @director = Director.new
    end
    def create
      @director = Director.new(director_params)
      if @director.save
         redirect_to directors_path
      else
         render 'new'
     end
    end
    def show
    end
    def edit
    end
    def update
        if @director.update(director_params)
            redirect_to director_path(@director)
        else
            render 'edit'
        end
    end
    def destroy
        @director.destroy
        redirect_to directors_path
    end

    private
    def director_params
        params[:director].permit!
    end

    def director_find
        @director = Director.find(params[:id])
    end

end

app/controllers/homes_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :work_find, only: [:edit, :show, :update, :destroy]

  def index
    @works = Work.all.by_position.page(params[:page]).per(9)
  end
  def show
  end
  def new
    @work = Work.new
    @work.director_id = params[:director_id] if params[:director_id].present?
  end
  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to works_path
    else
      render new
    end
  end
  def edit
  end
  def update
    if @work.update(work_params)
      redirect_to work_path(@work)
    else
      render 'edit'
    end
  end
  def destroy
    @work.destroy
    redirect_to works_path
  end

  def move_higher
    Work.find(params[:id]).move_higher
    redirect_to :action => 'index'
  end

  private

  def work_params
    params[:work].permit!
  end

  def work_find
    @work = Work.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/directors/_form.html.erb
  <%= bootstrap_form_with model: @director, local: true do |f| %>
    <%= f.text_field :Director %>
    <%= f.text_field :Country %>
    <%= f.file_field :image %>
    <%= f.submit %>
  <% end %>

app/views/directors/edit.html.erb
<section class="section site-portfolio">
<div class='container'>
  <h2>Edit Director data</h2>
  <%= render 'form' %>
  <%= link_to 'Delete', director_path(@director), method: :delete, data: {confirm: 'sss sure?'} %>
  <%= link_to 'Back', directors_path %>
</div>
</section>

app/views/directors/index.html.erb
<section class="section site-portfolio">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
        <h2>Directors index</h2>
        <p class="mb-0">Find you favorite movie!</p>
      </div>
      <div class="col-md-12 col-lg-6 text-left text-lg-right" data-aos="fade-up" data-aos-delay="100">
        <div class="filters" id="filters">
          <%= link_to 'Works', works_path %>
        </div>
      </div>
    </div>
    <div class="row no-gutter" id="portfolio-grid" data-aos="fade-up" data-aos-delay="200">
      <% @directors.each do |director|   %>
        <div class="item web col-sm-6 col-md-4 col-lg-4 mb-4">
          <%= link_to director_path(director), class: 'item-wrap fancybox' do %>
            <div class="work-info">
              <h3><%= director.Director %></h3>
            </div>
            <% if director.image_url %>
              <%= image_tag director.image_url(:thumb), class: 'img-fluid' %>
            <% else %>
              <img src='/img/default.png', class='img-fluid'>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <p>
      <%= link_to 'Add new director', new_director_path, class: 'btn btn-success' %>
    </p>
    <p>
      <%= link_to 'Go to Movie Index', works_path, class: 'btn btn-primary' %>
    </p>
  </div>
</section>

app/views/directors/new.html.erb
<section class="section site-portfolio"> 
<div class='container'> 
  <h2>Director form</h2>
  <%= render 'form' %>
  <br>
  <%= link_to 'Back', directors_path, class: 'btn btn-outline-info'%>
</div>
</section>

app/views/directors/show.html.erb
<section class="section site-portfolio">
<div class="container">
  <h5>Director data</h5><br>
  <h2><%= @director.Director %></h2>
</div>

<div class="container mt-3" data-aos="fade-up">
  <div class="row" id="portfolio-grid">
    <div class="col-8">
      <% if @director.image_url %>
        <%= image_tag @director.image_url, class: 'img-fluid mb-3' %>
      <% else %>
        <img src='/img/default.png', class='img-fluid mb-3'>
      <% end %>
    </div>
    <div class='col-4'>
      <div class="row mb-3 align-items-center"><%= @director.Country %></div>
    </div>
  </div>


    <%= link_to 'Edit', edit_director_path, class: 'btn btn-outline-info mr-2'%>
    <%= link_to 'Delete', director_path, method: :delete, data: {confirm: 'sure?'}, class: 'btn btn-outline-dark' %>
</div>

<div class="container mt-5" data-aos="fade-up">
  <h5>Other movies of <%= @director.Director %></h5><br>

  <div class="row no-gutter" id="portfolio-grid" data-aos="fade-up" data-aos-delay="200">
    <% @director.works.each do |work| %>
      <div class="item web col-sm-6 col-md-4 col-lg-4 mb-4">
        <%= link_to work_path(work), class: 'item-wrap fancybox' do %>
          <div class="work-info">
            <h3><%= work.Title %></h3>
            <span><%= work.ReleaseYear %></span>
            <br/>
            <span><%= work.director.Director %></span>
          </div>
          <% if work.image_url %>
            <%= image_tag work.image_url(:thumb), class: 'img-fluid' %>
          <% else %>
            <img src='/img/default.png', class='img-fluid'>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', directors_path, class: 'btn btn-primary mt-3 mb-3' %>
</div>

</section>

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta content='width=device-width, initial-scale=1.0' name='viewport'>
    <title>Movindex</title>
    <meta content='' name='descriptison'>
    <meta content='' name='keywords'>
    <!-- Favicons 
    <link href='assets/img/favicon.png' rel='icon'>
    <link href='assets/img/apple-touch-icon.png' rel='apple-touch-icon'>-->
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i' rel='stylesheet'>
    <!-- Vendor CSS Files -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <!-- ======= Navbar ======= -->
  <nav class='navbar navbar-light custom-navbar'>
    <div class='container'>
      <div class='navbar-brand'><%= link_to 'Movie Library', works_path%></div>
      <a class='burger' data-target='#main-navbar' data-toggle='collapse' href='#'>
        <span></span>
      </a>
    </div>
  </nav>
  
  <body>
    <%= yield %>
  </body>


  
  <!-- ======= footer ======= -->
  <footer class='footer' role='contentinfo'>
    <div class='container'>
      <div class='row'>
        <div class='col-sm-6'>
          <p class='mb-1'>© Copyright Movie Index</p>
          <div class='credits'>
            Designed by
            <a href='https://littlehackers.jp/'>dik</a>
          </div>
        </div>
        <div class='col-sm-6 social text-md-right'>
          <a href='#'>
            <span class='icofont-twitter'></span>
          </a>
          <a href='#'>
            <span class='icofont-facebook'></span>
          </a>
          <a href='#'>
            <span class='icofont-dribbble'></span>
          </a>
          <a href='#'>
            <span class='icofont-behance'></span>
          </a>
        </div>
      </div>
    </div>
    <a class='back-to-top' href='#'>
      <i class='icofont-simple-up'></i>
    </a>
  </footer>

<script src="/assets/aos/aos.js"></script>
<!-- 
<script src="/assets/store.legacry.min.js"></script>
<script src='https://cdn.jsdelivr.net/npm/store-js@2.0.4/dist/store.legacy.min.js'></script>

<%= javascript_include_tag "application" %> 
-->

</html>

app/views/works/_form.html.erb
<div class='container'>
  <%= bootstrap_form_with model: @work, local: true do |f| %>
    <%= f.text_field :Title %>
    <%= f.collection_select :director_id, Director.all, :id, :Director, include_blank: true, class: 'form-control' %>
    <%= f.text_field :ReleaseYear %>
    <%= f.text_field :Starring %>
    <%= f.text_field :Description %>
    <%= f.file_field :image  %>
    <%= f.submit 'Add movie', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/works/edit.html.erb
<section class="section site-portfolio">
<div class='container'>
  <h2>Edit Movie Data</h2>
  <%= render 'form' %>
  <p></p>
  <%= link_to 'Back', works_path, class: 'btn btn-outline-info' %>
</div>
</section>

app/views/works/index.html.erb
<section class="section site-portfolio">
  <div class="container">
    <div class="row mb-5 align-items-center">
      <div class="col-md-12 col-lg-6 mb-4 mb-lg-0" data-aos="fade-up">
        <h2>Movie index</h2>
        <p class="mb-0">Find you favorite movie!</p>
      </div>
      <div class="col-md-12 col-lg-6 text-left text-lg-right" data-aos="fade-up" data-aos-delay="100">
        <div class="filters" id="filters">
          <%= link_to 'Director', directors_path %>
        </div>
      </div>
    </div>
    <div class="row no-gutter" id="portfolio-grid" data-aos="fade-up" data-aos-delay="200">
      <% @works.each do |work| %>
        <div class="item web col-sm-6 col-md-4 col-lg-4 mb-4">
          <%= link_to work_path(work), class: 'item-wrap fancybox' do %>
            <div class="work-info">
              <h3><%= work.Title %></h3>
              <span><%= work.ReleaseYear %></span>
              <br/>
              <span><%= work.director.Director %></span>
            </div>
            <% if work.image_url %>
              <%= image_tag work.image_url(:thumb), class: 'img-fluid' %>
            <% else %>
              <img src='/img/default.png', class='img-fluid'>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <%= paginate @works, class: 'item web' %>
</div>

</section>
<div class="container">
  <%= link_to 'Add new movie', new_work_path, class: 'btn btn-outline-primary' %>
  <br/>
  <br/>
</div>

app/views/works/new.html.erb
<section class="section site-portfolio">

  <div class='container'>
    <h2>New Movie Data</h2><br>
    <%= render 'form' %>
    <br><br>
    <%= link_to 'Back', works_path, class: "btn btn-info" %>
  </div>
</section>

app/views/works/show.html.erb
<section class="section site-portfolio">
<div class="container">
  <h5>Movie data</h5><br>
  <h2><%= @work.Title %></h2>
  <div>Release: <%=@work.ReleaseYear%></div>
  <div>Starring: <%=@work.Starring %></h5></div><br>
</div>

<div class="container" data-aos="fade-up">
  <div class="row" id="portfolio-grid">
    <div class='col-sm-12 col-md-7 mb-4'>
      <% if @work.image_url %>
        <%= image_tag @work.image_url, class: 'img-fluid' %>
      <% else %>
        <img src='/img/img_5.jpg', class='img-fluid'>
      <% end %>
    </div>
    <div class='col-sm-12 col-md-5'>
      <div class="row mb-3 align-items-center"><%= @work.Description %></div>
      <div class="row align-items-center">Director:</div>
      <div class="row mb-3 align-items-center"><%= link_to @work.director.Director, director_path(@work.director_id) %></div>
    </div>
  </div>

  <%= link_to 'Edit', edit_work_path, class: 'btn btn-outline-info mr-2'%>
  <%= link_to 'Delete', work_path(@work), method: :delete, data: {confirm: 'sure?'}, class: 'btn btn-outline-dark' %><br>
  <%= link_to 'Back', works_path, class: 'btn btn-primary mt-3' %>
  
</div>
</section>